-- =============================================================================
-- VeloRent — Intelligent Vehicle Rental and Fleet Management System
-- FILE: 07_sample_data.sql
-- PURPOSE: Insert realistic Indian-context sample data.
--
-- INSERT ORDER (respects FK dependencies):
--   1. users
--   2. customers / admins / fleet_managers / maintenance_staff
--   3. vehicle_categories
--   4. vehicles
--   5. vehicle_features + vehicle_feature_mapping
--   6. loyalty_accounts
--   7. pricing_rules
--   8. bookings
--   9. rentals
--   10. payments
--   11. vehicle_inspections
--   12. damage_reports
--   13. maintenance
--   14. maintenance_logs
--   15. reviews
--   16. loyalty_transactions
--   17. waitlist
--   18. notifications
--   19. cancellation_records
--   20. vehicle_health_snapshots
--   21. system_logs (sample entries)
--
-- CONTEXT: Indian city of Bengaluru (Bangalore). INR currency.
--          Fleet operated by "VeloRent Bengaluru".
--
-- IMPORTANT: Triggers are ACTIVE during insert. The loyalty tier trigger,
--            audit trigger, and status triggers will fire. This is intentional
--            — it validates trigger correctness against real data.
--
-- RUN AFTER: 01_schema.sql through 06_triggers.sql
-- =============================================================================

USE velorent;

-- Disable FK checks during bulk load, re-enable at end.
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- =============================================================================
-- 1. USERS  (2 admins, 2 fleet managers, 2 maintenance staff, 30 customers)
-- =============================================================================
-- Passwords are shown as bcrypt placeholders (the real hash would be
-- generated by the C++ PasswordHasher). Format: bcrypt($2b$12$<salt><hash>)
-- All sample hashes here represent the password "VeloRent@2026"

INSERT INTO users (user_id, full_name, email, password_hash, phone, role, is_active, created_at) VALUES
-- ADMINS
(1,  'Arjun Mehta',          'arjun.mehta@velorent.in',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880001001', 'ADMIN',            TRUE, '2025-01-10 09:00:00'),
(2,  'Priya Sharma',         'priya.sharma@velorent.in',      '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880001002', 'ADMIN',            TRUE, '2025-01-10 09:15:00'),
-- FLEET MANAGERS
(3,  'Ravi Krishnamurthy',   'ravi.km@velorent.in',           '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880002001', 'FLEET_MANAGER',    TRUE, '2025-01-12 10:00:00'),
(4,  'Sunita Rao',           'sunita.rao@velorent.in',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880002002', 'FLEET_MANAGER',    TRUE, '2025-01-12 10:30:00'),
-- MAINTENANCE STAFF
(5,  'Mohammed Salim',       'salim.m@velorent.in',           '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880003001', 'MAINTENANCE_STAFF', TRUE, '2025-01-15 08:00:00'),
(6,  'Deepak Nair',          'deepak.nair@velorent.in',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9880003002', 'MAINTENANCE_STAFF', TRUE, '2025-01-15 08:30:00'),
-- CUSTOMERS (30)
(7,  'Aditya Kumar',         'aditya.kumar@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100001', 'CUSTOMER', TRUE, '2025-02-01 11:00:00'),
(8,  'Neha Gupta',           'neha.gupta@gmail.com',          '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100002', 'CUSTOMER', TRUE, '2025-02-03 12:00:00'),
(9,  'Rahul Verma',          'rahul.verma@yahoo.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100003', 'CUSTOMER', TRUE, '2025-02-05 09:30:00'),
(10, 'Pooja Singh',          'pooja.singh@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100004', 'CUSTOMER', TRUE, '2025-02-07 14:00:00'),
(11, 'Vikram Reddy',         'vikram.reddy@outlook.com',      '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100005', 'CUSTOMER', TRUE, '2025-02-10 10:00:00'),
(12, 'Ananya Pillai',        'ananya.pillai@gmail.com',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100006', 'CUSTOMER', TRUE, '2025-02-12 16:00:00'),
(13, 'Karan Malhotra',       'karan.malhotra@gmail.com',      '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100007', 'CUSTOMER', TRUE, '2025-02-15 09:00:00'),
(14, 'Shruti Menon',         'shruti.menon@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100008', 'CUSTOMER', TRUE, '2025-02-18 11:30:00'),
(15, 'Rohit Pandey',         'rohit.pandey@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100009', 'CUSTOMER', TRUE, '2025-02-20 08:00:00'),
(16, 'Kavita Iyer',          'kavita.iyer@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100010', 'CUSTOMER', TRUE, '2025-03-01 10:00:00'),
(17, 'Suresh Naidu',         'suresh.naidu@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100011', 'CUSTOMER', TRUE, '2025-03-05 13:00:00'),
(18, 'Meera Joshi',          'meera.joshi@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100012', 'CUSTOMER', TRUE, '2025-03-08 09:00:00'),
(19, 'Amitabh Das',          'amitabh.das@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100013', 'CUSTOMER', TRUE, '2025-03-12 15:00:00'),
(20, 'Lakshmi Venkat',       'lakshmi.venkat@gmail.com',      '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100014', 'CUSTOMER', TRUE, '2025-03-15 11:00:00'),
(21, 'Aryan Bose',           'aryan.bose@gmail.com',          '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100015', 'CUSTOMER', TRUE, '2025-03-20 10:30:00'),
(22, 'Divya Nambiar',        'divya.nambiar@gmail.com',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100016', 'CUSTOMER', TRUE, '2025-03-25 14:00:00'),
(23, 'Sanjay Kulkarni',      'sanjay.kulkarni@gmail.com',     '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100017', 'CUSTOMER', TRUE, '2025-04-01 09:00:00'),
(24, 'Tanya Kapoor',         'tanya.kapoor@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100018', 'CUSTOMER', TRUE, '2025-04-05 12:00:00'),
(25, 'Manoj Tiwari',         'manoj.tiwari@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100019', 'CUSTOMER', TRUE, '2025-04-10 10:00:00'),
(26, 'Ritu Bansal',          'ritu.bansal@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100020', 'CUSTOMER', TRUE, '2025-04-15 09:30:00'),
(27, 'Gautam Ahuja',         'gautam.ahuja@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100021', 'CUSTOMER', TRUE, '2025-04-20 11:00:00'),
(28, 'Rekha Shetty',         'rekha.shetty@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100022', 'CUSTOMER', TRUE, '2025-04-25 14:30:00'),
(29, 'Nikhil Saxena',        'nikhil.saxena@gmail.com',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100023', 'CUSTOMER', TRUE, '2025-05-01 10:00:00'),
(30, 'Pallavi Desai',        'pallavi.desai@gmail.com',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100024', 'CUSTOMER', TRUE, '2025-05-05 09:00:00'),
(31, 'Arun Subramanian',     'arun.subra@gmail.com',          '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100025', 'CUSTOMER', TRUE, '2025-05-10 10:00:00'),
(32, 'Swati Patil',          'swati.patil@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100026', 'CUSTOMER', TRUE, '2025-05-15 11:00:00'),
(33, 'Deepak Rajput',        'deepak.rajput@gmail.com',       '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100027', 'CUSTOMER', TRUE, '2025-05-20 09:30:00'),
(34, 'Geeta Bhatt',          'geeta.bhatt@gmail.com',         '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100028', 'CUSTOMER', TRUE, '2025-06-01 10:00:00'),
(35, 'Harish Gowda',         'harish.gowda@gmail.com',        '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100029', 'CUSTOMER', TRUE, '2025-06-05 14:00:00'),
(36, 'Isha Chatterjee',      'isha.chatterjee@gmail.com',     '$2b$12$LfmhPQWe9Z0sH8kXr1mLVOtY3nK7jA2B6cD4eF5gH0iJ1kL2mN3oP4', '9901100030', 'CUSTOMER', TRUE, '2025-06-10 12:00:00');

-- =============================================================================
-- 2. ROLE-SPECIFIC PROFILES
-- =============================================================================

INSERT INTO admins (admin_id, department, employee_code) VALUES
(1, 'Operations',         'ADM-BLR-001'),
(2, 'Customer Relations', 'ADM-BLR-002');

INSERT INTO fleet_managers (manager_id, employee_code, depot_location) VALUES
(3, 'FM-BLR-001', 'Whitefield Depot, Bengaluru'),
(4, 'FM-BLR-002', 'Koramangala Depot, Bengaluru');

INSERT INTO maintenance_staff (staff_id, employee_code, specialisation) VALUES
(5, 'MS-BLR-001', 'Engine and Mechanical'),
(6, 'MS-BLR-002', 'Bodywork and Electrical');

INSERT INTO customers
    (customer_id, date_of_birth, driving_licence_no, licence_expiry, address, city, state, pincode, risk_score, risk_label)
VALUES
(7,  '1992-03-15', 'KA-20-20120456789', '2030-03-14', '12, MG Road, Indiranagar',      'Bengaluru', 'Karnataka', '560038', 5.00,  'LOW'),
(8,  '1990-07-22', 'KA-20-20100234567', '2029-07-21', '34, 5th Cross, Koramangala',    'Bengaluru', 'Karnataka', '560034', 0.00,  'LOW'),
(9,  '1988-11-30', 'DL-01-20081234567', '2028-11-29', '78, Vasanth Nagar',             'Bengaluru', 'Karnataka', '560052', 12.00, 'LOW'),
(10, '1995-01-05', 'KA-20-20150789012', '2031-01-04', '23, HSR Layout, Sector 5',      'Bengaluru', 'Karnataka', '560102', 0.00,  'LOW'),
(11, '1985-09-18', 'AP-09-20050345678', '2027-09-17', '5, Sadashivanagar',             'Bengaluru', 'Karnataka', '560080', 35.00, 'MEDIUM'),
(12, '1993-04-12', 'KL-07-20130456789', '2030-04-11', '67, Bannerghatta Road',         'Bengaluru', 'Karnataka', '560076', 0.00,  'LOW'),
(13, '1991-06-25', 'KA-20-20110567890', '2029-06-24', '89, Brigade Road, Residency',   'Bengaluru', 'Karnataka', '560001', 18.00, 'LOW'),
(14, '1997-08-14', 'KL-09-20170678901', '2032-08-13', '102, Malleshwaram',             'Bengaluru', 'Karnataka', '560003', 0.00,  'LOW'),
(15, '1989-12-01', 'UP-14-20091234560', '2027-11-30', '45, Rajajinagar',               'Bengaluru', 'Karnataka', '560010', 42.00, 'MEDIUM'),
(16, '1994-02-28', 'KA-20-20140789012', '2030-02-27', '29, JP Nagar, 7th Phase',       'Bengaluru', 'Karnataka', '560078', 0.00,  'LOW'),
(17, '1987-05-10', 'AP-07-20070890123', '2027-05-09', '55, Yelahanka New Town',        'Bengaluru', 'Karnataka', '560064', 8.00,  'LOW'),
(18, '1996-10-20', 'MH-01-20161234567', '2031-10-19', '77, Electronic City Phase 1',   'Bengaluru', 'Karnataka', '560100', 0.00,  'LOW'),
(19, '1983-03-03', 'WB-01-20032345678', '2026-03-02', '33, Domlur Layout',             'Bengaluru', 'Karnataka', '560071', 60.00, 'HIGH'),
(20, '1998-07-15', 'KA-20-20180345678', '2033-07-14', '88, Whitefield Main Road',      'Bengaluru', 'Karnataka', '560066', 0.00,  'LOW'),
(21, '1992-11-22', 'KA-01-20120456789', '2030-11-21', '14, Hebbal, Ring Road',         'Bengaluru', 'Karnataka', '560024', 5.00,  'LOW'),
(22, '1990-01-30', 'KL-02-20100567890', '2029-01-29', '22, Jayanagar, 4th Block',      'Bengaluru', 'Karnataka', '560041', 0.00,  'LOW'),
(23, '1986-08-08', 'MH-14-20060678901', '2027-08-07', '66, Vijayanagar',               'Bengaluru', 'Karnataka', '560040', 15.00, 'LOW'),
(24, '1999-03-25', 'KA-20-20190789012', '2034-03-24', '11, Sarjapur Road',             'Bengaluru', 'Karnataka', '560035', 0.00,  'LOW'),
(25, '1984-06-12', 'UP-32-20040890123', '2026-06-11', '99, Marathahalli Bridge',       'Bengaluru', 'Karnataka', '560037', 25.00, 'MEDIUM'),
(26, '1995-09-05', 'KA-20-20150901234', '2030-09-04', '47, BTM Layout, 2nd Stage',     'Bengaluru', 'Karnataka', '560076', 0.00,  'LOW'),
(27, '1991-12-17', 'GJ-01-20111012345', '2029-12-16', '3, Cunningham Road',            'Bengaluru', 'Karnataka', '560052', 10.00, 'LOW'),
(28, '1988-04-23', 'KA-20-20081123456', '2027-04-22', '56, Kanakapura Road',           'Bengaluru', 'Karnataka', '560062', 0.00,  'LOW'),
(29, '1993-07-07', 'UP-65-20131234567', '2030-07-06', '74, Old Airport Road',          'Bengaluru', 'Karnataka', '560017', 20.00, 'LOW'),
(30, '1997-02-14', 'MH-43-20172345678', '2032-02-13', '38, Nandi Hills Road, Devanahalli', 'Bengaluru', 'Karnataka', '562110', 0.00, 'LOW'),
(31, '1989-08-30', 'TN-10-20090234567', '2027-08-29', '21, Rajiv Gandhi Nagar',        'Bengaluru', 'Karnataka', '560032', 0.00,  'LOW'),
(32, '1996-04-18', 'MH-12-20161234560', '2031-04-17', '63, Basaveshwara Nagar',        'Bengaluru', 'Karnataka', '560079', 5.00,  'LOW'),
(33, '1990-10-02', 'RJ-01-20101345678', '2029-10-01', '92, Yeshwanthpur',              'Bengaluru', 'Karnataka', '560022', 30.00, 'MEDIUM'),
(34, '1985-01-20', 'GJ-06-20052456789', '2026-01-19', '15, Chandra Layout',            'Bengaluru', 'Karnataka', '560040', 0.00,  'LOW'),
(35, '1994-06-28', 'KA-20-20140567890', '2030-06-27', '48, Mysore Road, Kengeri',      'Bengaluru', 'Karnataka', '560060', 0.00,  'LOW'),
(36, '1998-11-11', 'WB-06-20181678901', '2033-11-10', '7, Banashankari, 2nd Stage',    'Bengaluru', 'Karnataka', '560070', 0.00,  'LOW');

-- =============================================================================
-- 3. VEHICLE CATEGORIES
-- =============================================================================

INSERT INTO vehicle_categories (category_id, category_name, description, surcharge_pct) VALUES
(1, 'Hatchback',    'Compact city cars, fuel efficient, easy to park.',           0.00),
(2, 'Sedan',        'Family saloons offering comfort and boot space.',             5.00),
(3, 'SUV',          'Sports Utility Vehicles with higher ground clearance.',       15.00),
(4, 'Luxury',       'Premium vehicles with top-tier comfort and features.',        35.00),
(5, 'Electric',     'Battery-electric vehicles, zero direct emissions.',           10.00),
(6, 'Bike',         'Two-wheelers for city commutes and courier use.',             0.00),
(7, 'Premium Sedan','Business-class sedans, leather interior, sunroof.',           20.00);

-- =============================================================================
-- 4. VEHICLES  (50 vehicles)
-- =============================================================================
-- added_by values: 3 (Ravi) or 4 (Sunita), the two fleet managers.

INSERT INTO vehicles
    (vehicle_id, registration_no, brand, model, category_id, fuel_type, transmission,
     seats, purchase_year, colour, base_rate_per_day, odometer_km, health_score, status, added_by, created_at)
VALUES
-- HATCHBACKS (10)
(1,  'KA-01-MF-1001', 'Maruti',    'Swift',         1, 'PETROL',   'MANUAL',    5, 2022, 'Red',          1200.00,  28450,  87.50, 'AVAILABLE',   3, '2025-01-20 10:00:00'),
(2,  'KA-01-MF-1002', 'Maruti',    'WagonR',        1, 'CNG',      'MANUAL',    5, 2021, 'Silver',       1100.00,  42300,  78.00, 'AVAILABLE',   3, '2025-01-20 10:30:00'),
(3,  'KA-01-MF-1003', 'Hyundai',   'i20',           1, 'PETROL',   'AUTOMATIC', 5, 2023, 'Blue',         1400.00,  15200,  95.00, 'AVAILABLE',   4, '2025-01-21 09:00:00'),
(4,  'KA-01-MF-1004', 'Tata',      'Altroz',        1, 'DIESEL',   'MANUAL',    5, 2022, 'White',        1250.00,  33600,  83.00, 'AVAILABLE',   4, '2025-01-21 09:30:00'),
(5,  'KA-01-MF-1005', 'Maruti',    'Baleno',        1, 'PETROL',   'AUTOMATIC', 5, 2023, 'Grey',         1350.00,  18900,  93.50, 'RENTED',      3, '2025-01-22 10:00:00'),
(6,  'KA-01-MF-1006', 'Volkswagen','Polo',          1, 'PETROL',   'MANUAL',    5, 2020, 'Black',        1150.00,  56700,  72.00, 'AVAILABLE',   3, '2025-01-22 10:30:00'),
(7,  'KA-01-MF-1007', 'Renault',   'Kwid',          1, 'PETROL',   'MANUAL',    5, 2021, 'Orange',        900.00,  38000,  80.00, 'MAINTENANCE', 4, '2025-01-23 09:00:00'),
(8,  'KA-01-MF-1008', 'Hyundai',   'Santro',        1, 'CNG',      'MANUAL',    5, 2020, 'White',        1000.00,  47500,  71.00, 'AVAILABLE',   4, '2025-01-23 09:30:00'),
(9,  'KA-01-MF-1009', 'Tata',      'Tiago',         1, 'PETROL',   'MANUAL',    5, 2022, 'Teal',         1100.00,  29800,  85.00, 'AVAILABLE',   3, '2025-01-24 09:00:00'),
(10, 'KA-01-MF-1010', 'Maruti',    'Celerio',       1, 'CNG',      'AUTOMATIC', 5, 2023, 'Yellow',       1050.00,  12400,  97.00, 'RESERVED',    3, '2025-01-24 09:30:00'),
-- SEDANS (8)
(11, 'KA-01-MG-2001', 'Honda',     'City',          2, 'PETROL',   'AUTOMATIC', 5, 2022, 'Pearl White',  1800.00,  31200,  88.00, 'AVAILABLE',   3, '2025-01-25 10:00:00'),
(12, 'KA-01-MG-2002', 'Maruti',    'Dzire',         2, 'PETROL',   'MANUAL',    5, 2021, 'Silky Silver', 1500.00,  44100,  79.50, 'AVAILABLE',   4, '2025-01-25 10:30:00'),
(13, 'KA-01-MG-2003', 'Hyundai',   'Aura',          2, 'DIESEL',   'MANUAL',    5, 2022, 'Titan Grey',   1600.00,  37800,  82.00, 'AVAILABLE',   4, '2025-01-26 09:00:00'),
(14, 'KA-01-MG-2004', 'Toyota',    'Yaris',         2, 'PETROL',   'AUTOMATIC', 5, 2020, 'Avant Garde',  1700.00,  52100,  75.00, 'AVAILABLE',   3, '2025-01-26 09:30:00'),
(15, 'KA-01-MG-2005', 'Skoda',     'Slavia',        2, 'PETROL',   'AUTOMATIC', 5, 2023, 'Candy White',  2000.00,  14700,  96.00, 'RENTED',      3, '2025-01-27 10:00:00'),
(16, 'KA-01-MG-2006', 'Volkswagen','Vento',         2, 'PETROL',   'AUTOMATIC', 5, 2021, 'Reflex Silver',1750.00,  40300,  81.50, 'AVAILABLE',   4, '2025-01-27 10:30:00'),
(17, 'KA-01-MG-2007', 'Honda',     'Amaze',         2, 'DIESEL',   'MANUAL',    5, 2022, 'Radiant Red',  1550.00,  28900,  86.00, 'AVAILABLE',   4, '2025-01-28 09:00:00'),
(18, 'KA-01-MG-2008', 'Tata',      'Tigor',         2, 'PETROL',   'MANUAL',    5, 2021, 'Pure Silver',  1400.00,  35600,  82.50, 'AVAILABLE',   3, '2025-01-28 09:30:00'),
-- SUVs (10)
(19, 'KA-01-MH-3001', 'Hyundai',   'Creta',         3, 'DIESEL',   'AUTOMATIC', 5, 2023, 'Typhoon Silver',3200.00, 18700,  94.00, 'AVAILABLE',   3, '2025-01-29 10:00:00'),
(20, 'KA-01-MH-3002', 'Tata',      'Nexon',         3, 'DIESEL',   'MANUAL',    5, 2022, 'Calgary White', 2800.00, 29400,  87.00, 'RENTED',      4, '2025-01-29 10:30:00'),
(21, 'KA-01-MH-3003', 'Kia',       'Seltos',        3, 'PETROL',   'AUTOMATIC', 5, 2023, 'Glacier White', 3500.00, 16200,  96.50, 'AVAILABLE',   4, '2025-01-30 09:00:00'),
(22, 'KA-01-MH-3004', 'MG',        'Hector',        3, 'PETROL',   'AUTOMATIC', 7, 2022, 'Candy White',   3000.00, 31800,  85.50, 'AVAILABLE',   3, '2025-01-30 09:30:00'),
(23, 'KA-01-MH-3005', 'Mahindra',  'Scorpio-N',     3, 'DIESEL',   'MANUAL',    7, 2023, 'Deep Forest',   3300.00, 22100,  91.00, 'AVAILABLE',   3, '2025-01-31 10:00:00'),
(24, 'KA-01-MH-3006', 'Toyota',    'Fortuner',      3, 'DIESEL',   'AUTOMATIC', 7, 2021, 'Attitude Black',5500.00, 48200,  78.00, 'AVAILABLE',   4, '2025-01-31 10:30:00'),
(25, 'KA-01-MH-3007', 'Maruti',    'Brezza',        3, 'PETROL',   'AUTOMATIC', 5, 2023, 'Brave Khaki',   2600.00, 13400,  97.50, 'AVAILABLE',   4, '2025-02-01 09:00:00'),
(26, 'KA-01-MH-3008', 'Hyundai',   'Venue',         3, 'PETROL',   'AUTOMATIC', 5, 2022, 'Denim Blue',    2400.00, 24600,  89.50, 'RESERVED',    3, '2025-02-01 09:30:00'),
(27, 'KA-01-MH-3009', 'Ford',      'EcoSport',      3, 'DIESEL',   'MANUAL',    5, 2020, 'Moondust Silver',2200.00,58300,  68.00, 'MAINTENANCE', 4, '2025-02-02 09:00:00'),
(28, 'KA-01-MH-3010', 'Nissan',    'Magnite',       3, 'PETROL',   'AUTOMATIC', 5, 2022, 'Blade Silver',  2300.00, 27200,  88.00, 'AVAILABLE',   4, '2025-02-02 09:30:00'),
-- LUXURY (6)
(29, 'KA-01-ML-4001', 'BMW',       '3 Series',      4, 'PETROL',   'AUTOMATIC', 5, 2022, 'Mineral White', 9500.00, 24100,  90.00, 'AVAILABLE',   3, '2025-02-03 10:00:00'),
(30, 'KA-01-ML-4002', 'Mercedes',  'C-Class',       4, 'PETROL',   'AUTOMATIC', 5, 2023, 'Polar White',  11000.00, 11200,  97.00, 'AVAILABLE',   3, '2025-02-03 10:30:00'),
(31, 'KA-01-ML-4003', 'Audi',      'A4',            4, 'DIESEL',   'AUTOMATIC', 5, 2021, 'Floret Silver',10000.00, 38700,  83.00, 'AVAILABLE',   4, '2025-02-04 09:00:00'),
(32, 'KA-01-ML-4004', 'BMW',       '5 Series',      4, 'PETROL',   'AUTOMATIC', 5, 2022, 'Carbon Black', 12500.00, 27800,  88.50, 'RENTED',      4, '2025-02-04 09:30:00'),
(33, 'KA-01-ML-4005', 'Jaguar',    'XE',            4, 'DIESEL',   'AUTOMATIC', 5, 2021, 'Fuji White',   11500.00, 33400,  85.00, 'AVAILABLE',   3, '2025-02-05 09:00:00'),
(34, 'KA-01-ML-4006', 'Volvo',     'S90',           4, 'HYBRID',   'AUTOMATIC', 5, 2022, 'Osmium Grey',  13500.00, 19600,  93.00, 'AVAILABLE',   3, '2025-02-05 09:30:00'),
-- ELECTRIC (8)
(35, 'KA-01-ME-5001', 'Tata',      'Nexon EV',      5, 'ELECTRIC', 'AUTOMATIC', 5, 2023, 'Pristine White',3800.00, 18400,  96.00, 'AVAILABLE',   4, '2025-02-06 10:00:00'),
(36, 'KA-01-ME-5002', 'Tata',      'Tigor EV',      5, 'ELECTRIC', 'AUTOMATIC', 5, 2022, 'Daytona Grey',  2600.00, 24700,  92.00, 'AVAILABLE',   4, '2025-02-06 10:30:00'),
(37, 'KA-01-ME-5003', 'MG',        'ZS EV',         5, 'ELECTRIC', 'AUTOMATIC', 5, 2023, 'Aurora Red',    4500.00, 13200,  98.00, 'RENTED',      3, '2025-02-07 09:00:00'),
(38, 'KA-01-ME-5004', 'Hyundai',   'Kona Electric', 5, 'ELECTRIC', 'AUTOMATIC', 5, 2022, 'Surfy Blue',    5000.00, 22100,  91.50, 'AVAILABLE',   3, '2025-02-07 09:30:00'),
(39, 'KA-01-ME-5005', 'Ola',       'S1 Pro',        6, 'ELECTRIC', 'AUTOMATIC', 2, 2023, 'Jet Black',      600.00,  9800,  99.00, 'AVAILABLE',   4, '2025-02-08 09:00:00'),
(40, 'KA-01-ME-5006', 'Tata',      'Punch EV',      5, 'ELECTRIC', 'AUTOMATIC', 5, 2024, 'Fearless Purple',4200.00, 6700, 100.00, 'AVAILABLE',   4, '2025-02-08 09:30:00'),
(41, 'KA-01-ME-5007', 'BMW',       'iX1',           5, 'ELECTRIC', 'AUTOMATIC', 5, 2023, 'Alpine White',  9000.00, 15100,  95.00, 'AVAILABLE',   3, '2025-02-09 09:00:00'),
(42, 'KA-01-ME-5008', 'Mahindra',  'XEV 9e',        5, 'ELECTRIC', 'AUTOMATIC', 5, 2024, 'Burnt Umber',   7500.00,  4200, 100.00, 'RESERVED',    3, '2025-02-09 09:30:00'),
-- BIKES (8)
(43, 'KA-01-MB-6001', 'Royal Enfield','Classic 350', 6, 'PETROL',  'MANUAL',    2, 2022, 'Gunmetal Grey',  800.00, 22300,  88.00, 'AVAILABLE',   4, '2025-02-10 09:00:00'),
(44, 'KA-01-MB-6002', 'Honda',     'CB300R',        6, 'PETROL',   'MANUAL',    2, 2023, 'Mat Axis Grey',  750.00, 14100,  94.00, 'AVAILABLE',   4, '2025-02-10 09:30:00'),
(45, 'KA-01-MB-6003', 'Bajaj',     'Pulsar NS200',  6, 'PETROL',   'MANUAL',    2, 2022, 'Burnt Red',      650.00, 31800,  83.00, 'RENTED',      3, '2025-02-11 09:00:00'),
(46, 'KA-01-MB-6004', 'Yamaha',    'MT-15',         6, 'PETROL',   'MANUAL',    2, 2023, 'Ice Fluo',       700.00, 19200,  91.00, 'AVAILABLE',   3, '2025-02-11 09:30:00'),
(47, 'KA-01-MB-6005', 'KTM',       'Duke 200',      6, 'PETROL',   'MANUAL',    2, 2022, 'Orange',         750.00, 27600,  86.50, 'AVAILABLE',   4, '2025-02-12 09:00:00'),
(48, 'KA-01-MB-6006', 'Royal Enfield','Meteor 350',  6, 'PETROL',  'MANUAL',    2, 2023, 'Stellar Red',    820.00, 11700,  96.00, 'AVAILABLE',   4, '2025-02-12 09:30:00'),
(49, 'KA-01-MB-6007', 'Honda',     'Activa 6G',     6, 'PETROL',   'AUTOMATIC', 2, 2022, 'Pearl Siren Blue',450.00,24100,  85.00, 'AVAILABLE',   3, '2025-02-13 09:00:00'),
(50, 'KA-01-MB-6008', 'TVS',       'Jupiter',       6, 'PETROL',   'AUTOMATIC', 2, 2021, 'Matte Blue',     420.00, 38700,  76.00, 'AVAILABLE',   3, '2025-02-13 09:30:00');

-- =============================================================================
-- 5. VEHICLE FEATURES + MAPPING
-- =============================================================================

INSERT INTO vehicle_features (feature_id, feature_name) VALUES
(1,  'Air Conditioning'),
(2,  'GPS Navigation'),
(3,  'Bluetooth Audio'),
(4,  'Sunroof'),
(5,  'Rear Camera'),
(6,  'Android Auto / Apple CarPlay'),
(7,  'Keyless Entry'),
(8,  'Cruise Control'),
(9,  'Heated Seats'),
(10, 'Fast Charging Port (Type C)'),
(11, 'Child Safety Locks'),
(12, 'ABS + EBD'),
(13, 'Lane Assist'),
(14, 'Wireless Charger'),
(15, 'Ventilated Seats'),
(16, 'Premium Sound System'),
(17, 'Spare Tyre'),
(18, 'First Aid Kit');

-- Feature mapping (sample for key vehicles — not all 50 to keep insert readable)
INSERT INTO vehicle_feature_mapping (vehicle_id, feature_id) VALUES
-- Swift (1): AC, BT, ABS, Spare
(1, 1),(1, 3),(1, 12),(1, 17),
-- WagonR (2): AC, BT, ABS, Child, Spare
(2, 1),(2, 3),(2, 11),(2, 12),(2, 17),
-- i20 (3): AC, GPS, BT, Rear Cam, Android Auto, Keyless, ABS, Wireless, Spare
(3, 1),(3, 2),(3, 3),(3, 5),(3, 6),(3, 7),(3, 12),(3, 14),(3, 17),
-- Creta (19): Full features
(19, 1),(19, 2),(19, 3),(19, 4),(19, 5),(19, 6),(19, 7),(19, 8),(19, 12),(19, 14),(19, 17),(19, 18),
-- BMW 3 Series (29): All luxury
(29, 1),(29, 2),(29, 3),(29, 4),(29, 5),(29, 6),(29, 7),(29, 8),(29, 9),(29, 12),(29, 13),(29, 14),(29, 15),(29, 16),(29, 17),
-- Nexon EV (35): AC, GPS, BT, Rear Cam, Android Auto, Keyless, ABS, Type-C, Wireless
(35, 1),(35, 2),(35, 3),(35, 5),(35, 6),(35, 7),(35, 10),(35, 12),(35, 14),
-- Royal Enfield Classic 350 (43): ABS, Spare
(43, 12),(43, 17),
-- Honda City (11): AC, GPS, BT, Rear Cam, Android Auto, Keyless, ABS, Wireless
(11, 1),(11, 2),(11, 3),(11, 5),(11, 6),(11, 7),(11, 12),(11, 14),(11, 17),
-- Fortuner (24): Full SUV features
(24, 1),(24, 2),(24, 3),(24, 4),(24, 5),(24, 6),(24, 7),(24, 8),(24, 11),(24, 12),(24, 17),(24, 18),
-- Activa 6G (49): First Aid
(49, 17),(49, 18);

-- =============================================================================
-- 6. LOYALTY ACCOUNTS  (one per customer, user_ids 7–36)
-- =============================================================================
-- Disable the tier trigger temporarily because we're directly setting
-- the correct tier in the INSERT. Re-enable after.

INSERT INTO loyalty_accounts
    (loyalty_id, customer_id, points_balance, total_points_earned, tier, created_at)
VALUES
(1,  7,   2800,  3200, 'SILVER',   '2025-02-01 11:00:00'),
(2,  8,   5100,  6800, 'GOLD',     '2025-02-03 12:00:00'),
(3,  9,    200,   200, 'BRONZE',   '2025-02-05 09:30:00'),
(4,  10,  8500, 10000, 'GOLD',     '2025-02-07 14:00:00'),
(5,  11,   150,   150, 'BRONZE',   '2025-02-10 10:00:00'),
(6,  12, 16200, 17500, 'PLATINUM', '2025-02-12 16:00:00'),
(7,  13,   750,  1200, 'SILVER',   '2025-02-15 09:00:00'),
(8,  14,  3200,  3800, 'SILVER',   '2025-02-18 11:30:00'),
(9,  15,    80,    80, 'BRONZE',   '2025-02-20 08:00:00'),
(10, 16,  4600,  5200, 'GOLD',     '2025-03-01 10:00:00'),
(11, 17,  1500,  2100, 'SILVER',   '2025-03-05 13:00:00'),
(12, 18,  9800, 12400, 'GOLD',     '2025-03-08 09:00:00'),
(13, 19,    50,    50, 'BRONZE',   '2025-03-12 15:00:00'),
(14, 20,  6700,  7800, 'GOLD',     '2025-03-15 11:00:00'),
(15, 21,  2100,  2600, 'SILVER',   '2025-03-20 10:30:00'),
(16, 22,  3800,  4500, 'SILVER',   '2025-03-25 14:00:00'),
(17, 23,   600,   900, 'BRONZE',   '2025-04-01 09:00:00'),
(18, 24,  5500,  6200, 'GOLD',     '2025-04-05 12:00:00'),
(19, 25,   300,   300, 'BRONZE',   '2025-04-10 10:00:00'),
(20, 26,  7200,  8100, 'GOLD',     '2025-04-15 09:30:00'),
(21, 27,  1800,  2400, 'SILVER',   '2025-04-20 11:00:00'),
(22, 28,    0,     0,  'BRONZE',   '2025-04-25 14:30:00'),
(23, 29,  1200,  1600, 'SILVER',   '2025-05-01 10:00:00'),
(24, 30, 18500, 20000, 'PLATINUM', '2025-05-05 09:00:00'),
(25, 31,  4100,  5300, 'GOLD',     '2025-05-10 10:00:00'),
(26, 32,   900,  1050, 'SILVER',   '2025-05-15 11:00:00'),
(27, 33,   200,   450, 'BRONZE',   '2025-05-20 09:30:00'),
(28, 34,    0,     0,  'BRONZE',   '2025-06-01 10:00:00'),
(29, 35,  2700,  3300, 'SILVER',   '2025-06-05 14:00:00'),
(30, 36,    0,     0,  'BRONZE',   '2025-06-10 12:00:00');

-- =============================================================================
-- 7. PRICING RULES
-- =============================================================================

INSERT INTO pricing_rules (rule_id, rule_name, rule_type, multiplier, condition_json, is_active, effective_from, effective_to) VALUES
(1,  'Standard Rate',          'DEMAND',         1.0000, NULL,                                                          TRUE, NULL, NULL),
(2,  'High Demand Surge',      'DEMAND',         1.3000, '{"min_demand_ratio": 2.0}',                                   TRUE, NULL, NULL),
(3,  'Moderate Demand',        'DEMAND',         1.1500, '{"min_demand_ratio": 1.0, "max_demand_ratio": 2.0}',          TRUE, NULL, NULL),
(4,  'Low Demand Discount',    'DEMAND',         0.9000, '{"max_demand_ratio": 0.5}',                                   TRUE, NULL, NULL),
(5,  'Festival Season — Diwali','SEASONAL',      1.2500, '{"months": [10, 11]}',                                        TRUE, '2025-10-01', '2025-11-30'),
(6,  'New Year Surge',         'SEASONAL',       1.3500, '{"months": [12, 1]}',                                         TRUE, '2025-12-15', '2026-01-05'),
(7,  'Summer Holidays',        'SEASONAL',       1.1500, '{"months": [5, 6]}',                                          TRUE, '2025-05-01', '2025-06-30'),
(8,  'High Utilisation',       'UTILISATION',    1.2000, '{"min_utilisation_pct": 80}',                                 TRUE, NULL, NULL),
(9,  'Low Utilisation Promo',  'UTILISATION',    0.8500, '{"max_utilisation_pct": 30}',                                 TRUE, NULL, NULL),
(10, 'Silver Loyalty Discount','LOYALTY_DISCOUNT',0.9500,'{"tier": "SILVER"}',                                          TRUE, NULL, NULL),
(11, 'Gold Loyalty Discount',  'LOYALTY_DISCOUNT',0.9000,'{"tier": "GOLD"}',                                            TRUE, NULL, NULL),
(12, 'Platinum Loyalty Discount','LOYALTY_DISCOUNT',0.8500,'{"tier": "PLATINUM"}',                                      TRUE, NULL, NULL),
(13, 'EV Charging Surcharge',  'FUEL_SURCHARGE', 0.9500, '{"fuel_type": "ELECTRIC"}',                                   TRUE, NULL, NULL),
-- Slight discount on EVs to promote adoption
(14, 'Luxury Category Surcharge','CATEGORY_SURCHARGE',1.3500,'{"category": "Luxury"}',                                  TRUE, NULL, NULL),
(15, 'SUV Category Surcharge', 'CATEGORY_SURCHARGE',1.1500,'{"category": "SUV"}',                                       TRUE, NULL, NULL);

-- =============================================================================
-- 8. BOOKINGS  (mix of COMPLETED, CONFIRMED, CANCELLED, PENDING)
-- =============================================================================
-- Booking IDs and FK references are carefully ordered so inserts are valid.
-- customer_id = user_id for customers (7–36), vehicle_ids (1–50).

INSERT INTO bookings
    (booking_id, customer_id, vehicle_id, start_date, end_date, quoted_price, demand_factor, status, cancelled_at, cancellation_reason, created_at)
VALUES
-- COMPLETED bookings (past) — will have rentals associated
(1,  7,  11, '2025-03-01', '2025-03-05', 7560.00, 1.050, 'COMPLETED', NULL, NULL, '2025-02-25 10:00:00'),
(2,  8,  19, '2025-03-05', '2025-03-10', 16800.00, 1.000, 'COMPLETED', NULL, NULL, '2025-03-01 11:00:00'),
(3,  12, 30, '2025-03-10', '2025-03-14', 44000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-03-06 09:00:00'),
(4,  10, 21, '2025-03-15', '2025-03-20', 17500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-03-10 10:00:00'),
(5,  16, 35, '2025-03-20', '2025-03-25', 19000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-03-15 14:00:00'),
(6,  14, 29, '2025-04-01', '2025-04-04', 28500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-03-27 10:00:00'),
(7,  8,  1,  '2025-04-05', '2025-04-08', 3780.00, 1.050, 'COMPLETED', NULL, NULL, '2025-04-01 09:00:00'),
(8,  18, 37, '2025-04-10', '2025-04-15', 22500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-04-06 11:00:00'),
(9,  20, 24, '2025-04-15', '2025-04-20', 27500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-04-10 10:00:00'),
(10, 30, 32, '2025-04-20', '2025-04-25', 62500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-04-15 09:00:00'),
(11, 12, 21, '2025-05-01', '2025-05-06', 17500.00, 1.150, 'COMPLETED', NULL, NULL, '2025-04-26 10:00:00'),
(12, 26, 25, '2025-05-05', '2025-05-10', 13000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-05-01 11:00:00'),
(13, 24, 40, '2025-05-10', '2025-05-15', 21000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-05-06 09:00:00'),
(14, 31, 43, '2025-05-15', '2025-05-18', 2400.00, 1.000, 'COMPLETED', NULL, NULL, '2025-05-12 10:00:00'),
(15, 7,  12, '2025-05-20', '2025-05-25', 7500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-05-16 09:00:00'),
(16, 22, 16, '2025-06-01', '2025-06-05', 7000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-05-28 10:00:00'),
(17, 29, 9,  '2025-06-05', '2025-06-08', 3300.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-01 11:00:00'),
(18, 21, 36, '2025-06-10', '2025-06-15', 13000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-06 09:00:00'),
(19, 14, 34, '2025-06-15', '2025-06-20', 67500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-10 10:00:00'),
(20, 8,  22, '2025-06-20', '2025-06-25', 15000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-15 09:00:00'),
(21, 10, 44, '2025-07-01', '2025-07-04', 2250.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-27 10:00:00'),
(22, 18, 29, '2025-07-05', '2025-07-10', 47500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-07-01 09:00:00'),
(23, 30, 33, '2025-07-10', '2025-07-15', 57500.00, 1.000, 'COMPLETED', NULL, NULL, '2025-07-06 11:00:00'),
(24, 16, 19, '2025-07-15', '2025-07-20', 16000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-07-10 10:00:00'),
(25, 26, 38, '2025-07-20', '2025-07-25', 25000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-07-15 09:00:00'),
-- CANCELLED bookings
(26, 11, 5,  '2025-04-01', '2025-04-05', 6750.00, 1.000, 'CANCELLED', '2025-03-29 10:00:00', 'Change of plans', '2025-03-26 09:00:00'),
(27, 15, 23, '2025-05-01', '2025-05-05', 13200.00, 1.000, 'CANCELLED', '2025-04-28 11:00:00', 'Found cheaper option', '2025-04-25 10:00:00'),
(28, 19, 12, '2025-06-01', '2025-06-04', 4500.00, 1.000, 'CANCELLED', '2025-05-30 09:00:00', 'Emergency at home', '2025-05-27 10:00:00'),
(29, 25, 46, '2025-07-01', '2025-07-03', 1400.00, 1.000, 'CANCELLED', '2025-06-28 14:00:00', 'Bike not required', '2025-06-25 09:00:00'),
(30, 33, 15, '2025-08-01', '2025-08-05', 10000.00, 1.000, 'CANCELLED', '2025-07-29 10:00:00', 'Vehicle upgrade preferred', '2025-07-26 09:00:00'),
-- CONFIRMED bookings (active/upcoming)
(31, 7,  20, '2026-09-22', '2026-09-26', 11200.00, 1.000, 'CONFIRMED', NULL, NULL, '2026-09-18 10:00:00'),
(32, 9,  45, '2026-09-23', '2026-09-25', 1300.00,  1.000, 'CONFIRMED', NULL, NULL, '2026-09-19 11:00:00'),
(33, 16, 42, '2026-09-25', '2026-09-30', 37500.00, 1.000, 'CONFIRMED', NULL, NULL, '2026-09-20 09:00:00'),
-- ACTIVE bookings (rental in progress) — these have associated rentals
(34, 8,  5,  '2026-09-19', '2026-09-24', 6750.00,  1.050, 'CONFIRMED', NULL, NULL, '2026-09-15 10:00:00'),
(35, 18, 37, '2026-09-18', '2026-09-23', 22500.00, 1.000, 'CONFIRMED', NULL, NULL, '2026-09-14 09:00:00'),
(36, 12, 32, '2026-09-17', '2026-09-22', 62500.00, 1.000, 'CONFIRMED', NULL, NULL, '2026-09-13 10:00:00'),
-- Completed booking for Ford EcoSport (vehicle 27) — needed for damage report FK
-- This vehicle was rented, returned with SEVERE damage, and is now in MAINTENANCE.
(37, 23, 27, '2025-06-10', '2025-06-15', 11000.00, 1.000, 'COMPLETED', NULL, NULL, '2025-06-05 09:00:00');

-- =============================================================================
-- 9. RENTALS
-- =============================================================================
-- Rentals for COMPLETED bookings (booking_ids 1–25) and 3 currently ACTIVE.

INSERT INTO rentals
    (rental_id, booking_id, actual_start, actual_end, start_odometer, end_odometer, status)
VALUES
(1,  1,  '2025-03-01 09:30:00', '2025-03-05 10:00:00', 27800,  28450,  'COMPLETED'),
(2,  2,  '2025-03-05 10:00:00', '2025-03-10 11:00:00', 18100,  18700,  'COMPLETED'),
(3,  3,  '2025-03-10 09:00:00', '2025-03-14 10:00:00', 10800,  11200,  'COMPLETED'),
(4,  4,  '2025-03-15 10:00:00', '2025-03-20 09:30:00', 15600,  16200,  'COMPLETED'),
(5,  5,  '2025-03-20 09:00:00', '2025-03-25 10:00:00', 17800,  18400,  'COMPLETED'),
(6,  6,  '2025-04-01 10:00:00', '2025-04-04 11:00:00', 23500,  24100,  'COMPLETED'),
(7,  7,  '2025-04-05 09:00:00', '2025-04-08 10:00:00', 28100,  28450,  'COMPLETED'),
(8,  8,  '2025-04-10 09:30:00', '2025-04-15 10:00:00', 12700,  13200,  'COMPLETED'),
(9,  9,  '2025-04-15 10:00:00', '2025-04-20 09:30:00', 47600,  48200,  'COMPLETED'),
(10, 10, '2025-04-20 09:00:00', '2025-04-25 10:00:00', 27200,  27800,  'COMPLETED'),
(11, 11, '2025-05-01 09:30:00', '2025-05-06 10:00:00', 15900,  16200,  'COMPLETED'),
(12, 12, '2025-05-05 10:00:00', '2025-05-10 09:30:00', 13100,  13400,  'COMPLETED'),
(13, 13, '2025-05-10 09:00:00', '2025-05-15 10:00:00', 6200,   6700,   'COMPLETED'),
(14, 14, '2025-05-15 09:30:00', '2025-05-18 10:00:00', 21800,  22300,  'COMPLETED'),
(15, 15, '2025-05-20 10:00:00', '2025-05-25 09:30:00', 43600,  44100,  'COMPLETED'),
(16, 16, '2025-06-01 09:30:00', '2025-06-05 10:00:00', 39800,  40300,  'COMPLETED'),
(17, 17, '2025-06-05 10:00:00', '2025-06-08 09:30:00', 29300,  29800,  'COMPLETED'),
(18, 18, '2025-06-10 09:00:00', '2025-06-15 10:00:00', 24200,  24700,  'COMPLETED'),
(19, 19, '2025-06-15 10:00:00', '2025-06-20 09:30:00', 19100,  19600,  'COMPLETED'),
(20, 20, '2025-06-20 09:30:00', '2025-06-25 10:00:00', 31200,  31800,  'COMPLETED'),
(21, 21, '2025-07-01 09:00:00', '2025-07-04 10:00:00', 13700,  14100,  'COMPLETED'),
(22, 22, '2025-07-05 10:00:00', '2025-07-10 09:30:00', 23600,  24100,  'COMPLETED'),
(23, 23, '2025-07-10 09:30:00', '2025-07-15 10:00:00', 32800,  33400,  'COMPLETED'),
(24, 24, '2025-07-15 10:00:00', '2025-07-20 09:30:00', 18100,  18700,  'COMPLETED'),
(25, 25, '2025-07-20 09:00:00', '2025-07-25 10:00:00', 21600,  22100,  'COMPLETED'),
-- Ford EcoSport rental (booking 37) — returned with SEVERE damage
(29, 37, '2025-06-10 10:00:00', '2025-06-15 11:00:00', 57800,  58300,  'COMPLETED'),
-- ACTIVE rentals (currently in progress)
(26, 34, '2026-09-19 09:30:00', NULL,                   29900,  NULL,   'ACTIVE'),
(27, 35, '2026-09-18 10:00:00', NULL,                   12800,  NULL,   'ACTIVE'),
(28, 36, '2026-09-17 09:00:00', NULL,                   27400,  NULL,   'ACTIVE');

-- =============================================================================
-- 10. PAYMENTS  (for all completed rentals)
-- =============================================================================

INSERT INTO payments
    (payment_id, rental_id, amount, payment_method, payment_type, status,
     loyalty_points_used, transaction_ref, paid_at)
VALUES
(1,  1,  7560.00,  'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025030105421',  '2025-03-05 10:15:00'),
(2,  2,  16800.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-4523-20250310', '2025-03-10 11:30:00'),
(3,  3,  40000.00, 'CARD',        'BASE_RENT',    'COMPLETED', 800,  'CARD-8801-20250314', '2025-03-14 10:30:00'),
(4,  3,  4000.00,  'LOYALTY_POINTS','BASE_RENT',  'COMPLETED', 800,  NULL,                 '2025-03-14 10:30:00'),
(5,  4,  17500.00, 'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025032009422',  '2025-03-20 09:45:00'),
(6,  5,  15200.00, 'CARD',        'BASE_RENT',    'COMPLETED', 920,  'CARD-7712-20250325', '2025-03-25 10:30:00'),
(7,  5,  3800.00,  'LOYALTY_POINTS','BASE_RENT',  'COMPLETED', 760,  NULL,                 '2025-03-25 10:30:00'),
(8,  6,  28500.00, 'NET_BANKING', 'BASE_RENT',    'COMPLETED', 0,    'NB-HDFC-20250404',   '2025-04-04 11:30:00'),
(9,  7,  3780.00,  'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025040805233',  '2025-04-08 10:30:00'),
(10, 8,  22500.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-3301-20250415', '2025-04-15 10:30:00'),
(11, 9,  27500.00, 'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025042009321',  '2025-04-20 09:45:00'),
(12, 10, 62500.00, 'NET_BANKING', 'BASE_RENT',    'COMPLETED', 0,    'NB-ICICI-20250425',  '2025-04-25 10:30:00'),
(13, 11, 17500.00, 'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025050605311',  '2025-05-06 10:30:00'),
(14, 12, 13000.00, 'CASH',        'BASE_RENT',    'COMPLETED', 0,    NULL,                 '2025-05-10 09:45:00'),
(15, 13, 21000.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-6612-20250515', '2025-05-15 10:30:00'),
(16, 14, 2400.00,  'CASH',        'BASE_RENT',    'COMPLETED', 0,    NULL,                 '2025-05-18 10:15:00'),
(17, 15, 7500.00,  'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025052509122',  '2025-05-25 09:45:00'),
(18, 16, 7000.00,  'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-9901-20250605', '2025-06-05 10:30:00'),
(19, 17, 3300.00,  'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025060809411',  '2025-06-08 09:45:00'),
(20, 18, 13000.00, 'NET_BANKING', 'BASE_RENT',    'COMPLETED', 0,    'NB-SBI-20250615',    '2025-06-15 10:30:00'),
(21, 19, 67500.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-2210-20250620', '2025-06-20 09:45:00'),
(22, 20, 15000.00, 'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025062509221',  '2025-06-25 10:30:00'),
(23, 21, 2250.00,  'CASH',        'BASE_RENT',    'COMPLETED', 0,    NULL,                 '2025-07-04 10:15:00'),
(24, 22, 47500.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-5523-20250710', '2025-07-10 09:45:00'),
(25, 23, 57500.00, 'NET_BANKING', 'BASE_RENT',    'COMPLETED', 0,    'NB-AXIS-20250715',   '2025-07-15 10:30:00'),
(26, 24, 16000.00, 'UPI',         'BASE_RENT',    'COMPLETED', 0,    'UPI-2025072009411',  '2025-07-20 09:45:00'),
(27, 25, 25000.00, 'CARD',        'BASE_RENT',    'COMPLETED', 0,    'CARD-7723-20250725', '2025-07-25 10:30:00'),
-- Damage charge payment (for rental 7 — a minor dent)
(28, 7,  2500.00,  'UPI',         'DAMAGE_CHARGE','COMPLETED', 0,    'UPI-2025040805234',  '2025-04-08 10:45:00');

-- =============================================================================
-- 11. VEHICLE INSPECTIONS
-- =============================================================================

INSERT INTO vehicle_inspections
    (inspection_id, vehicle_id, inspector_id, inspection_type, health_score_given, odometer_reading, passed, notes, inspected_at)
VALUES
(1,  1,  5, 'PRE_RENTAL',   92.00, 27800, TRUE,  'All systems nominal. Tyres in good condition.',                        '2025-03-01 09:00:00'),
(2,  1,  5, 'POST_RENTAL',  87.50, 28450, TRUE,  'Minor dust accumulation. No damage observed.',                         '2025-03-05 10:00:00'),
(3,  11, 5, 'PRE_RENTAL',   90.00, 27800, TRUE,  'Clean interior, full fuel, all lights working.',                       '2025-03-01 09:00:00'),
(4,  11, 6, 'POST_RENTAL',  88.00, 28450, TRUE,  'Returned in good condition.',                                          '2025-03-05 10:00:00'),
(5,  19, 5, 'PRE_RENTAL',   96.00, 18100, TRUE,  'Excellent condition. ADAS sensors calibrated.',                        '2025-03-05 09:30:00'),
(6,  19, 6, 'POST_RENTAL',  94.00, 18700, TRUE,  'Normal wear. AC filter slightly dusty.',                               '2025-03-10 11:00:00'),
(7,  30, 5, 'PRE_RENTAL',   99.00, 10800, TRUE,  'Showroom condition. All luxury amenities functional.',                 '2025-03-10 08:30:00'),
(8,  30, 5, 'POST_RENTAL',  97.00, 11200, TRUE,  'Returned clean. Light fingerprints on dashboard.',                     '2025-03-14 10:00:00'),
(9,  1,  6, 'ROUTINE',      85.00, 28450, TRUE,  '6-month routine check. Oil change due in 1500 km.',                   '2025-04-15 09:00:00'),
(10, 19, 5, 'ROUTINE',      93.00, 18700, TRUE,  'All good. Tyre pressure adjusted.',                                    '2025-04-20 10:00:00'),
(11, 7,  5, 'DAMAGE',       55.00, 38000, FALSE, 'Front bumper cracked. Coolant leak detected. Immediate repair needed.','2025-05-10 09:00:00'),
(12, 27, 6, 'DAMAGE',       63.00, 58300, FALSE, 'Rear bumper dented. Left rear tyre worn out.',                        '2025-06-15 10:00:00'),
(13, 29, 5, 'PRE_RENTAL',   92.00, 23500, TRUE,  'Luxury interior pristine. All features functional.',                  '2025-04-01 09:30:00'),
(14, 29, 5, 'POST_RENTAL',  90.00, 24100, TRUE,  'Minor smudge on rear window. Otherwise perfect.',                     '2025-04-04 11:00:00'),
(15, 35, 6, 'PRE_RENTAL',   98.00, 17800, TRUE,  'Battery at 100%. All EV systems nominal.',                            '2025-03-20 09:00:00'),
(16, 35, 6, 'POST_RENTAL',  96.00, 18400, TRUE,  'Battery at 18%. Normal usage. No damage.',                            '2025-03-25 10:00:00');

-- =============================================================================
-- 12. DAMAGE REPORTS
-- NOTE: trg_after_damage_report_insert is ACTIVE.
--       When damage_report #3 (SEVERE, EcoSport) is inserted, the trigger
--       automatically:
--         (a) sets vehicle 27 status = 'MAINTENANCE'
--         (b) inserts a maintenance row (gets AUTO_INCREMENT id = 1)
--         (c) notifies all fleet managers
--       We do NOT insert a maintenance row for the EcoSport manually.
-- =============================================================================

INSERT INTO damage_reports
    (report_id, rental_id, vehicle_id, reported_by, severity, description,
     estimated_cost, actual_repair_cost, is_resolved, reported_at, resolved_at)
VALUES
-- Minor dent on Maruti Swift (rental 7, booking 7)
(1,  7,  1,  8,  'MINOR',    'Small dent on front left door. Paint scratched approximately 5 cm. Likely from parking.', 2500.00, 2200.00, TRUE, '2025-04-08 10:30:00', '2025-04-20 15:00:00'),
-- Moderate damage on Honda City (rental 15)
(2,  15, 12, 7,  'MODERATE', 'Rear bumper cracked. Passenger side mirror broken. Occurred during parking in narrow lane.', 8500.00, 9200.00, TRUE, '2025-05-25 09:45:00', '2025-06-05 14:00:00'),
-- SEVERE — Ford EcoSport (rental 29, booking 37, vehicle 27)
-- The trigger auto-creates maintenance_id=1 and sets vehicle 27 to MAINTENANCE.
(3,  29, 27, 5,  'SEVERE',   'Front bumper completely stoved in. Coolant leak. Airbag deployment warning light active. Vehicle requires immediate towing.', 35000.00, NULL, FALSE, '2025-06-15 11:00:00', NULL),
-- Minor scratch on BMW 5-Series (rental 10)
(4,  10, 32, 30, 'MINOR',    'Light scratches on driver side door. Likely from a shopping cart.', 3500.00, 3000.00, TRUE, '2025-04-25 10:45:00', '2025-05-05 16:00:00'),
-- Moderate damage on Fortuner (rental 9)
(5,  9,  24, 20, 'MODERATE', 'Left rear tyre puncture causing rim damage. Roadside assistance required.', 6500.00, 7000.00, TRUE, '2025-04-20 09:45:00', '2025-05-02 13:00:00');

-- =============================================================================
-- 13. MAINTENANCE
--
-- AUTO_INCREMENT ID ALLOCATION:
--   id=1  → Auto-created by trg_after_damage_report_insert when damage_report #3
--             (SEVERE, EcoSport vehicle 27) is inserted above. NOT inserted here.
--   id=2  → Routine service — Maruti Swift (vehicle 1)
--   id=3  → Repair         — Honda City (vehicle 12)   ← damage_report 2
--   id=4  → Routine         — Hyundai Creta (vehicle 19)
--   id=5  → Repair (IN_PROG)— Renault Kwid (vehicle 7)
--   id=6  → Emergency       — Tata Nexon EV (vehicle 35)
--   id=7  → Routine         — Royal Enfield Classic 350 (vehicle 43)
-- =============================================================================

INSERT INTO maintenance
    (maintenance_id, vehicle_id, damage_report_id, maintenance_type, priority,
     status, assigned_to, total_cost, description, scheduled_date,
     started_at, completed_at, created_at)
VALUES
-- id=2: Routine service for Maruti Swift (vehicle 1)
(2,  1,  NULL, 'ROUTINE',    'LOW',      'COMPLETED', 5, 4500.00,
    'Oil change, filter replacement, tyre rotation, brake inspection.',
    '2025-04-15', '2025-04-15 09:00:00', '2025-04-15 14:00:00', '2025-04-10 10:00:00'),
-- id=3: Repair for Honda City (vehicle 12) — linked to damage_report 2
(3,  12, 2,    'REPAIR',     'MEDIUM',   'COMPLETED', 6, 9200.00,
    'Rear bumper replacement and passenger side mirror replacement.',
    '2025-05-27', '2025-05-27 09:00:00', '2025-06-04 17:00:00', '2025-05-25 10:00:00'),
-- id=4: Routine service for Hyundai Creta (vehicle 19)
(4,  19, NULL, 'ROUTINE',    'LOW',      'COMPLETED', 5, 5800.00,
    'Full service: oil change, cabin filter, brake fluid flush, alignment.',
    '2025-05-15', '2025-05-15 09:00:00', '2025-05-15 16:00:00', '2025-05-10 09:00:00'),
-- id=5: Repair for Renault Kwid (vehicle 7) — inspection failure, IN_PROGRESS
(5,  7,  NULL, 'REPAIR',     'HIGH',     'IN_PROGRESS', 5, NULL,
    'Front bumper replacement and coolant system repair.',
    '2026-09-20', '2026-09-20 09:00:00', NULL, '2026-09-19 09:00:00'),
-- id=6: Emergency for Tata Nexon EV (vehicle 35) — DC charging port fault
(6,  35, NULL, 'EMERGENCY',  'CRITICAL', 'COMPLETED', 6, 12500.00,
    'DC Fast Charging port malfunction. Port replaced. Software update applied.',
    '2025-08-10', '2025-08-10 09:00:00', '2025-08-10 16:30:00', '2025-08-09 14:00:00'),
-- id=7: Routine service for Royal Enfield Classic 350 (vehicle 43)
(7,  43, NULL, 'ROUTINE',    'LOW',      'COMPLETED', 5, 2800.00,
    'Chain adjustment, oil change, tyre pressure, brake pad inspection.',
    '2025-09-01', '2025-09-01 09:00:00', '2025-09-01 13:00:00', '2025-08-28 10:00:00');

-- =============================================================================
-- 14. MAINTENANCE LOGS
--
-- maintenance_id FK map:
--   log 1 → maintenance_id 2 (Maruti Swift routine)
--   log 2 → maintenance_id 3 (Honda City repair)
--   log 3 → maintenance_id 4 (Creta routine)
--   log 4 → maintenance_id 5 (Kwid repair — IN_PROGRESS, partial log)
--   log 5 → maintenance_id 6 (Nexon EV emergency)
--   log 6 → maintenance_id 7 (Royal Enfield routine)
-- No log for maintenance_id 1 (EcoSport — auto-created by trigger, status OPEN)
-- =============================================================================

INSERT INTO maintenance_logs
    (log_id, maintenance_id, staff_id, notes, parts_used, cost_logged, logged_at)
VALUES
(1, 2, 5, 'Completed oil change with Mobil 1 Synthetic 5W-30. Replaced air filter. Rotated all 4 tyres. Brake pads at 60% — OK.',             'Engine Oil 4L, Air Filter',                  4500.00, '2025-04-15 14:00:00'),
(2, 3, 6, 'Removed damaged bumper. Fitted new OEM rear bumper. Replaced passenger side mirror assembly. Painted to match.',                    'Rear Bumper, Mirror Assy',                   9200.00, '2025-06-04 17:00:00'),
(3, 4, 5, 'Full service completed. Oil: Castrol Edge 5W-40. Cabin filter replaced. Brake fluid changed. Wheel alignment corrected.',           'Engine Oil 5L, Cabin Filter, Brake Fluid',   5800.00, '2025-05-15 16:00:00'),
(4, 5, 5, 'Started work on front bumper removal. Parts ordered. Coolant leak traced to radiator hose — replacement part arrives tomorrow.',   'Bumper (ordered)',                              0.00, '2026-09-20 14:00:00'),
(5, 6, 6, 'DC fast charging port removed and tested — confirmed faulty MOSFET. New port assembly installed. Software v2.4.1 update applied.', 'DC Charging Port Assy, Software Update',    12500.00, '2025-08-10 16:30:00'),
(6, 7, 5, 'Chain tension adjusted to spec. Engine oil changed. Tyre pressure set to 32 PSI front/rear. Brake pads at 70% — OK.',             'Engine Oil 1L',                               2800.00, '2025-09-01 13:00:00');

-- =============================================================================
-- 15. REVIEWS  (one per completed rental where customers are satisfied)
-- =============================================================================

INSERT INTO reviews
    (review_id, rental_id, customer_id, vehicle_id, rating, comment, is_flagged, created_at)
VALUES
(1,  1,  7,  11, 5, 'Spotless interior and very comfortable on the highway to Mysore. Smooth pickup process.', FALSE, '2025-03-06 10:00:00'),
(2,  2,  8,  19, 4, 'Comfortable suspension and powerful AC. Pickup depot was slightly crowded but staff was helpful.', FALSE, '2025-03-11 09:00:00'),
(3,  3,  12, 30, 5, 'Outstanding ride quality and pristine luxury cabin. Seamless check-in and checkout.', FALSE, '2025-03-15 11:00:00'),
(4,  4,  10, 21, 3, 'Decent car for city driving, but the touchscreen infotainment took some time to connect to Bluetooth.', FALSE, '2025-03-21 10:00:00'),
(5,  5,  16, 35, 5, 'Silent motor and instant acceleration. Fast-charging worked without issues at the expressway station.', FALSE, '2025-03-26 09:00:00'),
(6,  6,  14, 29, 5, 'Remarkable handling dynamics and crisp steering response. Pure driving pleasure on the bypass road.', FALSE, '2025-04-05 10:00:00'),
(7,  8,  18, 37, 4, 'Great regenerative braking and comfortable seating. City range was solid around 310 km.', FALSE, '2025-04-16 09:00:00'),
(8,  9,  20, 24, 4, 'Commanding road presence and massive boot capacity for our family weekend bags. A bit heavy to park in tight spots.', FALSE, '2025-04-21 10:00:00'),
(9,  10, 30, 32, 5, 'Executive comfort at its finest. Cabin soundproofing is sublime and highway cruise was effortless.', FALSE, '2025-04-26 09:00:00'),
(10, 11, 12, 21, 3, 'Overall ride was okay, but the tyre pressure warning came on 40 km into the trip. Resolved quickly at a fuel stop.', FALSE, '2025-05-07 10:00:00'),
(11, 12, 26, 25, 4, 'Reliable compact SUV with good ground clearance over speed breakers. Very fuel efficient.', FALSE, '2025-05-11 09:00:00'),
(12, 13, 24, 40, 5, 'Perfect urban commuter EV. Compact dimensions made street parking effortless and battery lasted two days.', FALSE, '2025-05-16 10:00:00'),
(13, 14, 31, 43, 5, 'Unmistakable exhaust thrum and comfortable upright posture for the morning highway ride.', FALSE, '2025-05-19 09:00:00'),
(14, 16, 22, 16, 4, 'Solid German build feel and planted highway manners. Infotainment interface feels slightly dated.', FALSE, '2025-06-06 10:00:00'),
(15, 17, 29, 9,  3, 'Good pocket-sized hatchback for tight city alleys. Engine was somewhat noisy under steep hill climbing.', FALSE, '2025-06-09 09:00:00'),
(16, 18, 21, 36, 4, 'Smooth electric delivery and easy regenerative slowing in stop-and-go traffic. Good value for money.', FALSE, '2025-06-16 10:00:00'),
(17, 19, 14, 34, 5, 'Immaculate Scandinavian aesthetics and supportive ergonomic seats. Incredible safety assist features.', FALSE, '2025-06-21 09:00:00'),
(18, 20, 8,  22, 3, 'Spacious panoramic cabin and generous legroom. Mileage was slightly thirsty in heavy downtown traffic.', FALSE, '2025-06-26 10:00:00'),
(19, 21, 10, 44, 4, 'Nimble chassis and responsive throttle. Great for weaving through evening peak-hour commutes.', FALSE, '2025-07-05 09:00:00'),
(20, 22, 18, 29, 5, 'Second time booking this exact 3 Series. The chassis balance and steering precision remain unmatched.', FALSE, '2025-07-11 10:00:00'),
(21, 23, 30, 33, 2, 'Driver seat adjustment was stiff and rear seat space was tighter than expected on our long highway route.', FALSE, '2025-07-16 09:00:00'),
(22, 24, 16, 19, 4, 'Smooth automatic gearbox and chilled ventilated seats. Handled the bumpy highway diversion with ease.', FALSE, '2025-07-21 10:00:00'),
(23, 25, 26, 38, 2, 'Vehicle drove smoothly, but the fast charging port flap was difficult to latch shut at the public charger.', FALSE, '2025-07-26 09:00:00'),
(24, 15, 7,  12, 5, 'Very smooth pickup and the car was spotless. Great experience overall.', FALSE, '2025-09-15 14:00:00');

-- =============================================================================
-- 16. LOYALTY TRANSACTIONS  (earn transactions matching completed rentals)
-- =============================================================================

INSERT INTO loyalty_transactions
    (txn_id, loyalty_id, txn_type, points, source, reference_id, created_at)
VALUES
-- Rental earn transactions (1 point per ₹100 rounded down)
(1,  1,  'EARN',   75,  'RENTAL_COMPLETE',       1,  '2025-03-05 10:15:00'),   -- customer 7, rental 1, ₹7560
(2,  2,  'EARN',   168, 'RENTAL_COMPLETE',       2,  '2025-03-10 11:30:00'),   -- customer 8, rental 2, ₹16800
(3,  6,  'EARN',   400, 'RENTAL_COMPLETE',       3,  '2025-03-14 10:30:00'),   -- customer 12, rental 3, ₹40000+4000
(4,  6,  'REDEEM', -800,'PAYMENT_REDEMPTION',    3,  '2025-03-14 10:30:00'),   -- customer 12 redeemed 800 pts
(5,  4,  'EARN',   175, 'RENTAL_COMPLETE',       4,  '2025-03-20 09:45:00'),   -- customer 10, rental 4
(6,  10, 'EARN',   190, 'RENTAL_COMPLETE',       5,  '2025-03-25 10:30:00'),   -- customer 16, rental 5
(7,  10, 'REDEEM', -760,'PAYMENT_REDEMPTION',    5,  '2025-03-25 10:30:00'),   -- customer 16 redeemed
(8,  8,  'EARN',   285, 'RENTAL_COMPLETE',       6,  '2025-04-04 11:30:00'),   -- customer 14, rental 6
(9,  2,  'EARN',   37,  'RENTAL_COMPLETE',       7,  '2025-04-08 10:30:00'),   -- customer 8, rental 7
(10, 12, 'EARN',   225, 'RENTAL_COMPLETE',       8,  '2025-04-15 10:30:00'),   -- customer 18, rental 8
(11, 14, 'EARN',   275, 'RENTAL_COMPLETE',       9,  '2025-04-20 09:45:00'),   -- customer 20, rental 9
(12, 24, 'EARN',   625, 'RENTAL_COMPLETE',       10, '2025-04-25 10:30:00'),   -- customer 30, rental 10
(13, 6,  'EARN',   175, 'RENTAL_COMPLETE',       11, '2025-05-06 10:30:00'),   -- customer 12, rental 11
(14, 20, 'EARN',   130, 'RENTAL_COMPLETE',       12, '2025-05-10 09:45:00'),   -- customer 26, rental 12
(15, 18, 'EARN',   210, 'RENTAL_COMPLETE',       13, '2025-05-15 10:30:00'),   -- customer 24, rental 13
(16, 25, 'EARN',   24,  'RENTAL_COMPLETE',       14, '2025-05-18 10:15:00'),   -- customer 31, rental 14
(17, 1,  'EARN',   75,  'RENTAL_COMPLETE',       15, '2025-05-25 09:45:00'),   -- customer 7, rental 15
(18, 16, 'EARN',   70,  'RENTAL_COMPLETE',       16, '2025-06-05 10:30:00'),   -- customer 22, rental 16
(19, 23, 'EARN',   33,  'RENTAL_COMPLETE',       17, '2025-06-08 09:45:00'),   -- customer 29, rental 17
(20, 15, 'EARN',   130, 'RENTAL_COMPLETE',       18, '2025-06-15 10:30:00'),   -- customer 21, rental 18
(21, 8,  'EARN',   675, 'RENTAL_COMPLETE',       19, '2025-06-20 09:45:00'),   -- customer 14, rental 19
(22, 2,  'EARN',   150, 'RENTAL_COMPLETE',       20, '2025-06-25 10:30:00'),   -- customer 8, rental 20
(23, 4,  'EARN',   22,  'RENTAL_COMPLETE',       21, '2025-07-04 10:15:00'),   -- customer 10, rental 21
(24, 12, 'EARN',   475, 'RENTAL_COMPLETE',       22, '2025-07-10 09:45:00'),   -- customer 18, rental 22
(25, 24, 'EARN',   575, 'RENTAL_COMPLETE',       23, '2025-07-15 10:30:00'),   -- customer 30, rental 23
(26, 10, 'EARN',   160, 'RENTAL_COMPLETE',       24, '2025-07-20 09:45:00'),   -- customer 16, rental 24
(27, 20, 'EARN',   250, 'RENTAL_COMPLETE',       25, '2025-07-25 10:30:00');   -- customer 26, rental 25

-- =============================================================================
-- 17. WAITLIST
-- =============================================================================

INSERT INTO waitlist
    (waitlist_id, customer_id, vehicle_id, requested_start, requested_end,
     status, notified_at, queued_at)
VALUES
(1,  9,  30, '2026-10-01', '2026-10-05', 'WAITING',   NULL,                     '2026-09-18 09:00:00'),
(2,  13, 32, '2026-10-10', '2026-10-15', 'WAITING',   NULL,                     '2026-09-19 10:00:00'),
(3,  17, 37, '2026-09-23', '2026-09-28', 'WAITING',   NULL,                     '2026-09-19 11:00:00'),
(4,  23, 29, '2026-10-05', '2026-10-08', 'WAITING',   NULL,                     '2026-09-20 09:00:00'),
(5,  25, 45, '2026-10-01', '2026-10-03', 'WAITING',   NULL,                     '2026-09-20 10:00:00'),
-- Historical — fulfilled or expired
(6,  11, 1,  '2025-03-01', '2025-03-05', 'FULFILLED', NULL,                     '2025-02-28 09:00:00'),
(7,  15, 5,  '2025-04-01', '2025-04-05', 'NOTIFIED',  '2025-03-29 10:05:00',    '2025-03-25 10:00:00'),
(8,  19, 12, '2025-06-01', '2025-06-04', 'EXPIRED',   NULL,                     '2025-05-28 09:00:00');

-- =============================================================================
-- 18. NOTIFICATIONS
-- =============================================================================

-- =============================================================================
-- 18. NOTIFICATIONS
-- =============================================================================

INSERT INTO notifications
    (user_id, notification_type, title, message, reference_id, is_read, created_at)
VALUES
(7,  'BOOKING_CONFIRMED',    'Booking Confirmed',                  'Your booking for Honda City (KA-01-MG-2001) from Mar 1 to Mar 5 is confirmed. Amount: ₹7,560.',             1,  TRUE,  '2025-02-25 10:05:00'),
(8,  'BOOKING_CONFIRMED',    'Booking Confirmed',                  'Your booking for Hyundai Creta (KA-01-MH-3001) from Mar 5 to Mar 10 is confirmed. Amount: ₹16,800.',        2,  TRUE,  '2025-03-01 11:05:00'),
(7,  'RENTAL_COMPLETED',     'Rental Complete — Thank You!',       'Your rental of Honda City has been completed. You earned 75 VeloPoints! Please leave a review.',            1,  TRUE,  '2025-03-05 10:30:00'),
(8,  'RENTAL_COMPLETED',     'Rental Complete — Thank You!',       'Your rental of Hyundai Creta has been completed. You earned 168 VeloPoints!',                                2,  TRUE,  '2025-03-10 11:45:00'),
(12, 'LOYALTY_TIER_UPGRADE', 'You are now PLATINUM!',             'Congratulations Ananya! You have reached PLATINUM tier with 15,000+ lifetime VeloPoints. Enjoy 15% off!',  NULL, TRUE, '2025-05-06 10:35:00'),
(15, 'WAITLIST_NOTIFIED',    'Vehicle Now Available',              'A vehicle you waitlisted (Maruti Baleno) is now available for your dates (Apr 1–Apr 5). Confirm in 24h!',  7,  TRUE,  '2025-03-29 10:05:00'),
(14, 'PAYMENT_RECEIVED',     'Payment Received',                   'Payment of ₹28,500 received for your BMW 3 Series rental. Invoice #INV-00006.',                           6,  TRUE,  '2025-04-04 11:35:00'),
(30, 'PAYMENT_RECEIVED',     'Payment Received',                   'Payment of ₹62,500 received for your BMW 5 Series rental. Invoice #INV-00010.',                           10, TRUE,  '2025-04-25 10:45:00'),
(9,  'WAITLIST_NOTIFIED',    'Vehicle Now Available',              'A vehicle you waitlisted (Mercedes C-Class ID: 30) is now available for Oct 1–Oct 5. Confirm in 24h!',    1,  FALSE, '2026-09-20 10:00:00'),
(8,  'BOOKING_CONFIRMED',    'Booking Confirmed',                  'Your booking for Maruti Baleno (KA-01-MF-1005) from Sep 19 to Sep 24 is confirmed. Amount: ₹6,750.',       34, FALSE, '2026-09-15 10:05:00'),
(18, 'BOOKING_CONFIRMED',    'Booking Confirmed',                  'Your booking for MG ZS EV (KA-01-ME-5003) from Sep 18 to Sep 23 is confirmed. Amount: ₹22,500.',          35, FALSE, '2026-09-14 09:05:00'),
(12, 'BOOKING_CONFIRMED',    'Booking Confirmed',                  'Your booking for BMW 5 Series (KA-01-ML-4004) from Sep 17 to Sep 22 is confirmed. Amount: ₹62,500.',      36, FALSE, '2026-09-13 10:05:00'),
(30, 'LOYALTY_TIER_UPGRADE', 'You are now PLATINUM!',             'Congratulations Pallavi! You have reached PLATINUM tier with 20,000+ lifetime VeloPoints. Enjoy 15% off!',NULL, TRUE, '2025-04-26 09:05:00');

-- =============================================================================
-- 19. CANCELLATION RECORDS
-- =============================================================================

INSERT INTO cancellation_records
    (cancellation_id, booking_id, cancelled_by, reason, refund_amount, refund_status, cancelled_at)
VALUES
(1, 26, 11, 'Change of plans due to personal emergency.',                         0.00,    'NOT_APPLICABLE', '2025-03-29 10:00:00'),
(2, 27, 15, 'Found a cheaper alternative vehicle elsewhere.',                     6600.00, 'PROCESSED',      '2025-04-28 11:00:00'),
(3, 28, 19, 'Family emergency required immediate travel. Could not proceed.',     2250.00, 'PROCESSED',      '2025-05-30 09:00:00'),
(4, 29, 25, 'Bike no longer required. Trip cancelled.',                           0.00,    'NOT_APPLICABLE', '2025-06-28 14:00:00'),
(5, 30, 33, 'Preferred to upgrade to a luxury sedan instead.',                   5000.00, 'PENDING',        '2025-07-29 10:00:00');

-- =============================================================================
-- 20. VEHICLE HEALTH SNAPSHOTS  (historical health trend data)
-- =============================================================================

INSERT INTO vehicle_health_snapshots (vehicle_id, health_score, computed_by, recorded_at) VALUES
(1,  95.00, 'INSPECTION', '2025-01-20 10:00:00'),
(1,  92.00, 'INSPECTION', '2025-03-01 09:00:00'),
(1,  87.50, 'INSPECTION', '2025-03-05 10:00:00'),
(1,  85.00, 'INSPECTION', '2025-04-15 09:00:00'),
(11, 95.00, 'INSPECTION', '2025-01-25 10:00:00'),
(11, 90.00, 'INSPECTION', '2025-03-01 09:00:00'),
(11, 88.00, 'INSPECTION', '2025-03-05 10:00:00'),
(19, 99.00, 'ENGINE',     '2025-01-29 10:00:00'),
(19, 96.00, 'INSPECTION', '2025-03-05 09:30:00'),
(19, 94.00, 'INSPECTION', '2025-03-10 11:00:00'),
(19, 93.00, 'INSPECTION', '2025-04-20 10:00:00'),
(7,  88.00, 'ENGINE',     '2025-01-23 09:00:00'),
(7,  72.00, 'ENGINE',     '2025-03-15 10:00:00'),
(7,  55.00, 'INSPECTION', '2025-05-10 09:00:00'),
(27, 80.00, 'ENGINE',     '2025-02-02 09:30:00'),
(27, 63.00, 'INSPECTION', '2025-06-15 10:00:00'),
(29, 99.00, 'ENGINE',     '2025-02-03 10:00:00'),
(29, 92.00, 'INSPECTION', '2025-04-01 09:30:00'),
(29, 90.00, 'INSPECTION', '2025-04-04 11:00:00'),
(35, 100.00,'ENGINE',     '2025-02-06 10:00:00'),
(35, 98.00, 'INSPECTION', '2025-03-20 09:00:00'),
(35, 96.00, 'INSPECTION', '2025-03-25 10:00:00');

-- =============================================================================
-- 21. SYSTEM LOGS (sample entries — triggers also write to this table,
--     so IDs are NOT specified here; AUTO_INCREMENT picks the next free value)
-- =============================================================================

INSERT INTO system_logs
    (actor_id, actor_role, action, entity_type, entity_id, old_value, new_value, ip_address, performed_at)
VALUES
(1,  'ADMIN',           'USER_CREATED',            'user',       7,  NULL,                                  JSON_OBJECT('user_id',7,'email','aditya.kumar@gmail.com','role','CUSTOMER'),                       '192.168.1.1', '2025-02-01 11:00:00'),
(3,  'FLEET_MANAGER',   'VEHICLE_ADDED',           'vehicle',    1,  NULL,                                  JSON_OBJECT('vehicle_id',1,'registration','KA-01-MF-1001','brand','Maruti','model','Swift'),        '192.168.1.5', '2025-01-20 10:05:00'),
(7,  'CUSTOMER',        'BOOKING_CREATED',         'booking',    1,  NULL,                                  JSON_OBJECT('booking_id',1,'vehicle_id',11,'start_date','2025-03-01'),                              '10.0.0.12',   '2025-02-25 10:01:00'),
(1,  'ADMIN',           'VEHICLE_STATUS_CHANGED',  'vehicle',    7,  JSON_OBJECT('status','AVAILABLE'),     JSON_OBJECT('status','MAINTENANCE'),                                                                '192.168.1.1', '2025-05-10 09:05:00'),
(5,  'MAINTENANCE_STAFF','MAINTENANCE_COMPLETED',  'maintenance',1,  JSON_OBJECT('status','IN_PROGRESS'),   JSON_OBJECT('status','COMPLETED','total_cost',4500),                                                '192.168.1.8', '2025-04-15 14:05:00'),
(8,  'CUSTOMER',        'BOOKING_CANCELLED',       'booking',    7,  JSON_OBJECT('status','CONFIRMED'),     JSON_OBJECT('status','CANCELLED'),                                                                  '10.0.0.15',   '2025-04-08 10:50:00'),
(1,  'ADMIN',           'USER_DEACTIVATED',        'user',       19, JSON_OBJECT('is_active',TRUE),         JSON_OBJECT('is_active',FALSE),                                                                    '192.168.1.1', '2025-09-01 10:00:00'),
(3,  'FLEET_MANAGER',   'VEHICLE_ADDED',           'vehicle',    35, NULL,                                  JSON_OBJECT('vehicle_id',35,'registration','KA-01-ME-5001','brand','Tata','model','Nexon EV'),      '192.168.1.5', '2025-02-06 10:05:00'),
(NULL,'SYSTEM',         'HEALTH_SCORE_UPDATED',    'vehicle',    1,  JSON_OBJECT('health_score',87.50),     JSON_OBJECT('health_score',85.00),                                                                  NULL,          '2025-04-15 14:05:00'),
(12, 'CUSTOMER',        'REVIEW_SUBMITTED',        'review',     3,  NULL,                                  JSON_OBJECT('review_id',3,'rental_id',3,'rating',5),                                               '10.0.0.20',   '2025-03-15 11:05:00');

-- Re-enable FK checks
SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- VALIDATION QUERIES — counts confirm all data loaded correctly
-- =============================================================================

SELECT 'users'               AS tbl, COUNT(*) AS `rows` FROM users
UNION ALL
SELECT 'customers',                  COUNT(*)             FROM customers
UNION ALL
SELECT 'vehicles',                   COUNT(*)             FROM vehicles
UNION ALL
SELECT 'vehicle_categories',         COUNT(*)             FROM vehicle_categories
UNION ALL
SELECT 'bookings',                   COUNT(*)             FROM bookings
UNION ALL
SELECT 'rentals',                    COUNT(*)             FROM rentals
UNION ALL
SELECT 'payments',                   COUNT(*)             FROM payments
UNION ALL
SELECT 'damage_reports',             COUNT(*)             FROM damage_reports
UNION ALL
SELECT 'maintenance',                COUNT(*)             FROM maintenance
UNION ALL
SELECT 'maintenance_logs',           COUNT(*)             FROM maintenance_logs
UNION ALL
SELECT 'reviews',                    COUNT(*)             FROM reviews
UNION ALL
SELECT 'loyalty_accounts',           COUNT(*)             FROM loyalty_accounts
UNION ALL
SELECT 'loyalty_transactions',       COUNT(*)             FROM loyalty_transactions
UNION ALL
SELECT 'waitlist',                   COUNT(*)             FROM waitlist
UNION ALL
SELECT 'notifications',              COUNT(*)             FROM notifications
UNION ALL
SELECT 'pricing_rules',              COUNT(*)             FROM pricing_rules
UNION ALL
SELECT 'cancellation_records',       COUNT(*)             FROM cancellation_records
UNION ALL
SELECT 'vehicle_health_snapshots',   COUNT(*)             FROM vehicle_health_snapshots
UNION ALL
SELECT 'system_logs',                COUNT(*)             FROM system_logs;

-- =============================================================================
-- END OF SAMPLE DATA
-- =============================================================================
