'use client';

import React, { useState, useEffect } from 'react';
import { ProtectedRoute } from '@/components/auth/ProtectedRoute';
import { AppShell } from '@/components/layout/AppShell';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { IntelligenceAlertCard } from '@/components/fleet/IntelligenceAlertCard';
import { getFleetInsights } from '@/lib/api/admin';
import { getPricingQuote } from '@/lib/api/pricing';
import { FleetInsight, PricingQuote, LoyaltyTier } from '@/types';
import { Sparkles, Calculator, AlertCircle } from 'lucide-react';

export default function FleetIntelligencePage() {
  const [insights, setInsights] = useState<FleetInsight[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Dynamic Pricing Simulation State
  const [simVehicleId, setSimVehicleId] = useState<string>('1');
  const [simStartDate, setSimStartDate] = useState<string>('2026-10-01');
  const [simEndDate, setSimEndDate] = useState<string>('2026-10-05');
  const [simDemandFactor, setSimDemandFactor] = useState<string>('1.2');
  const [simTier, setSimTier] = useState<LoyaltyTier>('BRONZE');
  const [simQuote, setSimQuote] = useState<PricingQuote | null>(null);
  const [isSimulating, setIsSimulating] = useState(false);
  const [simError, setSimError] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    const fetchIntelligenceData = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const insList = await getFleetInsights();
        if (mounted) {
          setInsights(insList);
        }
      } catch (err) {
        if (mounted) setError(err instanceof Error ? err.message : 'Failed to load intelligence insights.');
      } finally {
        if (mounted) setIsLoading(false);
      }
    };

    fetchIntelligenceData();
    return () => {
      mounted = false;
    };
  }, []);

  const handleRunPricingSim = async (e: React.FormEvent) => {
    e.preventDefault();
    const vId = parseInt(simVehicleId, 10);
    const demand = parseFloat(simDemandFactor);

    if (isNaN(vId) || vId <= 0) {
      setSimError('Please enter a valid numeric Vehicle ID.');
      return;
    }

    setIsSimulating(true);
    setSimError(null);
    setSimQuote(null);

    try {
      const quote = await getPricingQuote({
        vehicleId: vId,
        startDate: simStartDate,
        endDate: simEndDate,
        demandFactor: isNaN(demand) ? 1.0 : demand,
        loyaltyTier: simTier,
      });
      setSimQuote(quote);
    } catch (err) {
      setSimError(err instanceof Error ? err.message : 'Pricing simulation failed.');
    } finally {
      setIsSimulating(false);
    }
  };

  const highPriority = insights.filter((i) => i.severity === 'CRITICAL' || i.severity === 'HIGH');
  const mediumPriority = insights.filter((i) => i.severity === 'MEDIUM');
  const lowPriority = insights.filter((i) => i.severity === 'LOW' || i.severity === 'INFO');

  return (
    <ProtectedRoute allowedRoles={['FLEET_MANAGER']}>
      <AppShell>
        <PageHeader
          title="Fleet Intelligence & Pricing Decision Engine"
          description="Operational alerts generated by C++ FleetIntelligenceEngine and dynamic pricing simulation powered by PricingEngine."
        />

        {error && (
          <div className="mb-6 p-4 bg-rose-50 border border-rose-200 text-rose-700 text-xs rounded-xl flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Intelligence Engine Alerts */}
          <div className="lg:col-span-2 space-y-6">
            <div>
              <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-blue-600" /> Operational Insights & Alerts
              </h3>

              {isLoading ? (
                <div className="p-6 bg-white border border-slate-200 rounded-xl text-xs text-slate-500">
                  Executing C++ intelligence engine scan...
                </div>
              ) : insights.length > 0 ? (
                <div className="space-y-4">
                  {highPriority.length > 0 && (
                    <div className="space-y-3">
                      <span className="text-xs font-bold text-rose-700 uppercase tracking-wider block">
                        High Priority Alerts ({highPriority.length})
                      </span>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {highPriority.map((ins, idx) => (
                          <IntelligenceAlertCard key={idx} insight={ins} />
                        ))}
                      </div>
                    </div>
                  )}

                  {mediumPriority.length > 0 && (
                    <div className="space-y-3 pt-2">
                      <span className="text-xs font-bold text-amber-700 uppercase tracking-wider block">
                        Medium Priority Alerts ({mediumPriority.length})
                      </span>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {mediumPriority.map((ins, idx) => (
                          <IntelligenceAlertCard key={idx} insight={ins} />
                        ))}
                      </div>
                    </div>
                  )}

                  {lowPriority.length > 0 && (
                    <div className="space-y-3 pt-2">
                      <span className="text-xs font-bold text-blue-700 uppercase tracking-wider block">
                        Standard Operational Signals ({lowPriority.length})
                      </span>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {lowPriority.map((ins, idx) => (
                          <IntelligenceAlertCard key={idx} insight={ins} />
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="p-6 bg-white border border-slate-200 rounded-xl text-xs text-slate-500">
                  No active operational alerts flagged by C++ FleetIntelligenceEngine.
                </div>
              )}
            </div>
          </div>

          {/* Pricing Engine Quote Simulation Tool */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-sm flex items-center gap-2">
                  <Calculator className="w-4 h-4 text-emerald-600" /> C++ PricingEngine Quote Simulator
                </CardTitle>
              </CardHeader>
              <CardContent className="px-6 pb-6 pt-0 space-y-4">
                <p className="text-xs text-slate-600 leading-relaxed">
                  Test backend dynamic pricing calculations for duration discounts, demand multipliers, and loyalty tiers.
                </p>

                <form onSubmit={handleRunPricingSim} className="space-y-3">
                  <Input
                    label="Vehicle ID"
                    type="number"
                    min={1}
                    value={simVehicleId}
                    onChange={(e) => setSimVehicleId(e.target.value)}
                    required
                  />

                  <div className="grid grid-cols-2 gap-2">
                    <Input
                      label="Start Date"
                      type="date"
                      value={simStartDate}
                      onChange={(e) => setSimStartDate(e.target.value)}
                      required
                    />
                    <Input
                      label="End Date"
                      type="date"
                      value={simEndDate}
                      onChange={(e) => setSimEndDate(e.target.value)}
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">
                      Demand Factor Multiplier
                    </label>
                    <Input
                      type="number"
                      step="0.1"
                      min={0.5}
                      max={3.0}
                      value={simDemandFactor}
                      onChange={(e) => setSimDemandFactor(e.target.value)}
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">
                      Customer Loyalty Tier
                    </label>
                    <select
                      value={simTier}
                      onChange={(e) => setSimTier(e.target.value as LoyaltyTier)}
                      className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs font-medium focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="BRONZE">BRONZE (0% discount)</option>
                      <option value="SILVER">SILVER (5% discount)</option>
                      <option value="GOLD">GOLD (10% discount)</option>
                      <option value="PLATINUM">PLATINUM (15% discount)</option>
                    </select>
                  </div>

                  <Button
                    type="submit"
                    size="sm"
                    className="w-full"
                    isLoading={isSimulating}
                    leftIcon={<Calculator className="w-4 h-4" />}
                  >
                    Calculate Dynamic Quote
                  </Button>
                </form>

                {simError && (
                  <div className="p-3 bg-rose-50 border border-rose-200 text-rose-700 text-xs rounded-lg flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    <span>{simError}</span>
                  </div>
                )}

                {/* Simulated Pricing Quote Breakdown */}
                {simQuote && (
                  <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-3 text-xs pt-3">
                    <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                      <span className="text-slate-500">Base Rate / Day</span>
                      <span className="font-bold text-slate-900 tabular-nums">₹{simQuote.baseRatePerDay.toLocaleString()}</span>
                    </div>

                    <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                      <span className="text-slate-500">Duration ({simQuote.durationDays} days) Subtotal</span>
                      <span className="font-bold text-slate-900 tabular-nums">₹{simQuote.subtotal.toLocaleString()}</span>
                    </div>

                    {simQuote.demandAdjustment > 0 && (
                      <div className="flex items-center justify-between text-amber-700 border-b border-slate-200 pb-2">
                        <span>Demand Factor Adjustment</span>
                        <span className="font-bold tabular-nums">+₹{simQuote.demandAdjustment.toLocaleString()}</span>
                      </div>
                    )}

                    {simQuote.durationDiscount > 0 && (
                      <div className="flex items-center justify-between text-emerald-700 border-b border-slate-200 pb-2">
                        <span>Duration Discount</span>
                        <span className="font-bold tabular-nums">-₹{simQuote.durationDiscount.toLocaleString()}</span>
                      </div>
                    )}

                    {simQuote.loyaltyDiscount > 0 && (
                      <div className="flex items-center justify-between text-indigo-700 border-b border-slate-200 pb-2">
                        <span>Loyalty Tier ({simTier}) Discount</span>
                        <span className="font-bold tabular-nums">-₹{simQuote.loyaltyDiscount.toLocaleString()}</span>
                      </div>
                    )}

                    <div className="flex items-center justify-between pt-1">
                      <span className="font-extrabold text-slate-900">Final Calculated Price</span>
                      <span className="text-base font-extrabold text-blue-600 tabular-nums">
                        ₹{simQuote.finalPrice.toLocaleString()}
                      </span>
                    </div>

                    <div className="pt-2 border-t border-slate-200 text-[11px] text-slate-600">
                      <strong className="block text-slate-800 mb-0.5">Rationale:</strong>
                      {simQuote.explanation}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </AppShell>
    </ProtectedRoute>
  );
}
